## Numpy - Numerical Python

In [1]:
import numpy as np

In [2]:
# create an array
a = np.array([12,3,5,7])
a

array([12,  3,  5,  7])

In [3]:
# checking dimension of an array
a.ndim

1

In [4]:
# create a two dimensional array with numpy
b=np.array([[1,2],[3,4]])
b


array([[1, 2],
       [3, 4]])

In [5]:
b.ndim

2

In [6]:
# create a three dimensional array with numpy
p=np.array([[[1, 2,3], [3, 4,5], [6, 7,8]]])
p



array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [7]:
p. ndim

3

## Zero's and One's

In [8]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create a 3 dimensional array with 4 rows and 5 columns & all the elements should be 1

In [12]:
s= np.ones((3,4,5))

In [13]:
s

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Functions use in numpy

In [18]:
var = np.array([22,43,14,55,45])

In [19]:
var

array([22, 43, 14, 55, 45])

In [20]:
type(var)

numpy.ndarray

In [21]:
var.argmax() # max value in index position

3

In [22]:
var.argmin() #min index value

2

In [23]:
var[2]

14

In [24]:
var1 = np.array([22,43,14,55,45,12,98,75])
var1

array([22, 43, 14, 55, 45, 12, 98, 75])

In [27]:
var1[:5]

array([22, 43, 14, 55, 45])

In [28]:
var1[2:-2]

array([14, 55, 45, 12])

In [30]:
var1.dtype

dtype('int64')

In [33]:
var2 = np.array([22.1,43,14,55,45,12,98,75])
var2

array([22.1, 43. , 14. , 55. , 45. , 12. , 98. , 75. ])

In [32]:
var2.dtype

dtype('float64')

In [34]:
var1

array([22, 43, 14, 55, 45, 12, 98, 75])

In [35]:
var1.size

8

In [36]:
# create a numpy with size 5 and datatype of floating point

x = np.array([1.1,2,3,4,5])
x


array([1.1, 2. , 3. , 4. , 5. ])

In [37]:
x.size

5

In [38]:
x.dtype

dtype('float64')

In [ ]:
# create a two dimensional array
# four arrays in the external array
# it should have two elements in each

In [39]:
a= np.array([[1,2],[2,3],[5,6],[7,8]])
a


array([[1, 2],
       [2, 3],
       [5, 6],
       [7, 8]])

## Resize and reshape

In [40]:
a1 = np.arange(12)

In [41]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a1.ndim

1

In [43]:
r = np.arange(12).reshape(4,3)
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
r.max()

11

In [45]:
r.min()

0

In [46]:
np.sqrt(r)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [47]:
np.log(r)

<ipython-input-47-487c15201b95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(r)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [48]:
np.exp(r)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [49]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
r.shape

(4, 3)

## Transpose

In [51]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
t = r.T
t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [53]:
t.shape

(3, 4)

## Floor and Ceil

In [59]:
 arr2 = np.array([10.3,3.42,5.6,1,8.8,2.3])
 arr2

array([10.3 ,  3.42,  5.6 ,  1.  ,  8.8 ,  2.3 ])

In [60]:
np.floor(arr2)

array([10.,  3.,  5.,  1.,  8.,  2.])

In [61]:
np.round(arr2)

array([10.,  3.,  6.,  1.,  9.,  2.])

In [62]:
np.ceil(arr2)

array([11.,  4.,  6.,  1.,  9.,  3.])

## Stacking

In [63]:
arr23 = np.arange(10).reshape(2,5)
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
arr24 = np.arange(20).reshape(4,5)
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
np.hstack((arr23,arr24))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [68]:
arr25 = np.arange(10).reshape(2,5)
arr25

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
arr26 = np.arange(20).reshape(2,10)
arr26

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [70]:
np.hstack((arr25,arr26))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
# for vstack number of columns should be same for two arrays,and for hstack,number of rows should be same.

## Numpy split

In [71]:
arr12 = np.arange(100).reshape(10,10)

In [72]:
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
np.vsplit(arr12,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [74]:
np.hsplit(arr12,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
# create a numpy array with shape of 200, array should be contains 20 rows and 10 columns
# split the array into vertically and horizondally

In [75]:
arr13 = np.arange(200).reshape(20,10)

In [76]:
arr13

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [77]:
np.vsplit(arr13,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181,

In [78]:
np.hsplit(arr13,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,